var stimuli_pratique_v1 = [
	{
        version: 1,
		bloc: 0,
        ordre_logique: 3,
        ordre_tache: "p1",
        complexite: "pratique",
        position_emotion: "pratique",
        emotion: "neutre",
        sexe: "M",
        phrase: "sound/pensif.wav",
        image1: "img/pensif.jpeg",
        image2: "img/heureux.jpeg",
        image3: "img/furieux.jpeg",
        bonne_reponse: 37,
        bonne_image: "img/pensif.jpeg"
    },
    {
        version: 1,
		bloc: 0,
        ordre_logique: 6,
        ordre_tache: "p2",
        complexite: "pratique",
        position_emotion: "pratique",
        emotion: "furieux",
        sexe: "F",
        phrase: "sound/furieuse.wav",
        image1: "img/pensive.jpeg",
        image2: "img/heureuse.jpeg",
        image3: "img/furieuse.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/furieuse.jpeg"
    },
    
    {
        version: 1,
		bloc: 0,
        ordre_logique: 1,
        ordre_tache: "p3",
        complexite: "pratique",
        position_emotion: "pratique",
        emotion: "heureux",
        sexe: "M",
        phrase: "sound/heureux.wav",
        image1: "img/furieux.jpeg",
        image2: "img/pensif.jpeg",
        image3: "img/heureux.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/heureux.jpeg"
    },
    {
        version: 1,
		bloc: 0,
        ordre_logique: 4,
        ordre_tache: "p4",
        complexite: "pratique",
        position_emotion: "pratique",
        emotion: "neutre",
        sexe: "F",
        phrase: "sound/pensive.wav",
        image1: "img/furieuse.jpeg",
        image2: "img/pensive.jpeg",
        image3: "img/heureuse.jpeg",
        bonne_reponse: 40,
        bonne_image: "img/pensive.jpeg"
    },
    {
        version: 1,
		bloc: 0,
        ordre_logique: 2,
        ordre_tache: "p5",
        complexite: "pratique",
        position_emotion: "pratique",
        emotion: "heureux",
        sexe: "F",
        phrase: "sound/heureuse.wav",
        image1: "img/heureuse.jpeg",
        image2: "img/furieuse.jpeg",
        image3: "img/pensive.jpeg",
        bonne_reponse: 37,
        bonne_image: "img/heureuse.jpeg"
    },
	{
        version: 1,
		bloc: 0,
        ordre_logique: 5,
        ordre_tache: "p6",
        complexite: "pratique",
        position_emotion: "pratique",
        emotion: "furieux",
        sexe: "M",
        phrase: "sound/furieux.wav",
        image1: "img/heureux.jpeg",
        image2: "img/furieux.jpeg",
        image3: "img/pensif.jpeg",
        bonne_reponse: 40,
        bonne_image: "img/furieux.jpeg"
    },
];
var stimuli_bloc1_v1 = [
    {
        version: 1,
        bloc: 1,
        ordre_logique: 22,
        ordre_tache: "a1",
        complexite: "complexe",
        position_emotion: "eo",
        emotion: "neutre",
        sexe: "F",
        phrase: "sound/complexe-eo-4.m4a",
        image1: "img/Diapositive64.jpeg",
        image2: "img/Diapositive65.jpeg",
        image3: "img/Diapositive66.jpeg",
        bonne_reponse: 37,
        bonne_image: "img/Diapositive64.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 23,
        ordre_tache: "a2",
        complexite: "complexe",
        position_emotion: "eo",
        emotion: "furieux",
        sexe: "M",
        phrase: "sound/complexe-eo-5.m4a",
        image1: "img/Diapositive69.jpeg",
        image2: "img/Diapositive68.jpeg",
        image3: "img/Diapositive67.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/Diapositive67.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 2,
        ordre_tache: "a3",
        complexite: "simple",
        position_emotion: "es",
        emotion: "heureux",
        sexe: "F",
        phrase: "sound/simple-es-2.m4a",
        image1: "img/Diapositive6.jpeg",
        image2: "img/Diapositive5.jpeg",
        image3: "img/Diapositive4.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/Diapositive4.jpeg", 
    },
];

var stimuli_bloc2_v1 = [
    {
        version: 1,
		bloc: 2,
        ordre_logique: 5,
        ordre_tache: "a1",
        complexite: "simple",
        position_emotion: "es",
        emotion: "furieux",
        sexe: "M",
        phrase: "sound/simple-es-5.m4a",
        image1: "img/Diapositive86.jpeg",
        image2: "img/Diapositive87.jpeg",
        image3: "img/Diapositive85.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/Diapositive85.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 10,
        ordre_tache: "a2",
        complexite: "simple",
        position_emotion: "eo",
        emotion: "neutre",
        sexe: "F",
        phrase: "sound/simple-eo-4.m4a",
        image1: "img/Diapositive102.jpeg",
        image2: "img/Diapositive100.jpeg",
        image3: "img/Diapositive101.jpeg",
        bonne_reponse: 40,
        bonne_image: "img/Diapositive100.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 14,
        ordre_tache: "a3",
        complexite: "complexe",
        position_emotion: "es",
        emotion: "heureux",
        sexe: "F",
        phrase: "sound/complexe-es-2.m4a",
        image1: "img/Diapositive114.jpeg",
        image2: "img/Diapositive113.jpeg",
        image3: "img/Diapositive112.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/Diapositive112.jpeg", 
    },
];