var stimuli_pratique_v1 = [
	{
        version: 1,
		bloc: 0,
        ordre_logique: 3,
        ordre_tache: "p1",
        complexite: "pratique",
        position_emotion: "pratique",
        emotion: "neutre",
        sexe: "M",
        phrase: "sound/pensif.wav",
        image1: "img/pensif.jpeg",
        image2: "img/heureux.jpeg",
        image3: "img/furieux.jpeg",
        bonne_reponse: 37,
        bonne_image: "img/pensif.jpeg"
    },
    {
        version: 1,
		bloc: 0,
        ordre_logique: 6,
        ordre_tache: "p2",
        complexite: "pratique",
        position_emotion: "pratique",
        emotion: "furieux",
        sexe: "F",
        phrase: "sound/furieuse.wav",
        image1: "img/pensive.jpeg",
        image2: "img/heureuse.jpeg",
        image3: "img/furieuse.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/furieuse.jpeg"
    },
    
    {
        version: 1,
		bloc: 0,
        ordre_logique: 1,
        ordre_tache: "p3",
        complexite: "pratique",
        position_emotion: "pratique",
        emotion: "heureux",
        sexe: "M",
        phrase: "sound/heureux.wav",
        image1: "img/furieux.jpeg",
        image2: "img/pensif.jpeg",
        image3: "img/heureux.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/heureux.jpeg"
    },
    {
        version: 1,
		bloc: 0,
        ordre_logique: 4,
        ordre_tache: "p4",
        complexite: "pratique",
        position_emotion: "pratique",
        emotion: "neutre",
        sexe: "F",
        phrase: "sound/pensive.wav",
        image1: "img/furieuse.jpeg",
        image2: "img/pensive.jpeg",
        image3: "img/heureuse.jpeg",
        bonne_reponse: 40,
        bonne_image: "img/pensive.jpeg"
    },
    {
        version: 1,
		bloc: 0,
        ordre_logique: 2,
        ordre_tache: "p5",
        complexite: "pratique",
        position_emotion: "pratique",
        emotion: "heureux",
        sexe: "F",
        phrase: "sound/heureuse.wav",
        image1: "img/heureuse.jpeg",
        image2: "img/furieuse.jpeg",
        image3: "img/pensive.jpeg",
        bonne_reponse: 37,
        bonne_image: "img/heureuse.jpeg"
    },
	{
        version: 1,
		bloc: 0,
        ordre_logique: 5,
        ordre_tache: "p6",
        complexite: "pratique",
        position_emotion: "pratique",
        emotion: "furieux",
        sexe: "M",
        phrase: "sound/furieux.wav",
        image1: "img/heureux.jpeg",
        image2: "img/furieux.jpeg",
        image3: "img/pensif.jpeg",
        bonne_reponse: 40,
        bonne_image: "img/furieux.jpeg"
    },
];

var stimuli_bloc1_v1 = [
    {
        version: 1,
        bloc: 1,
        ordre_logique: 22,
        ordre_tache: "a1",
        complexite: "complexe",
        position_emotion: "eo",
        emotion: "neutre",
        sexe: "F",
        phrase: "sound/complexe-eo-4.m4a",
        image1: "img/Diapositive64.jpeg",
        image2: "img/Diapositive65.jpeg",
        image3: "img/Diapositive66.jpeg",
        bonne_reponse: 37,
        bonne_image: "img/Diapositive64.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 23,
        ordre_tache: "a2",
        complexite: "complexe",
        position_emotion: "eo",
        emotion: "furieux",
        sexe: "M",
        phrase: "sound/complexe-eo-5.m4a",
        image1: "img/Diapositive69.jpeg",
        image2: "img/Diapositive68.jpeg",
        image3: "img/Diapositive67.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/Diapositive67.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 2,
        ordre_tache: "a3",
        complexite: "simple",
        position_emotion: "es",
        emotion: "heureux",
        sexe: "F",
        phrase: "sound/simple-es-2.m4a",
        image1: "img/Diapositive6.jpeg",
        image2: "img/Diapositive5.jpeg",
        image3: "img/Diapositive4.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/Diapositive4.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 18,
        ordre_tache: "b1",
        complexite: "complexe",
        position_emotion: "es",
        emotion: "furieux",
        sexe: "F",
        phrase: "sound/complexe-es-6.m4a",
        image1: "img/Diapositive54.jpeg",
        image2: "img/Diapositive53.jpeg",
        image3: "img/Diapositive52.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/Diapositive52.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 19,
        ordre_tache: "b2",
        complexite: "complexe",
        position_emotion: "eo",
        emotion: "heureux",
        sexe: "M",
        phrase: "sound/complexe-eo-1.m4a",
        image1: "img/Diapositive56.jpeg",
        image2: "img/Diapositive57.jpeg",
        image3: "img/Diapositive55.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/Diapositive55.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 9,
        ordre_tache: "b3",
        complexite: "simple",
        position_emotion: "eo",
        emotion: "neutre",
        sexe: "M",
        phrase: "sound/simple-eo-3.m4a",
        image1: "img/Diapositive27.jpeg",
        image2: "img/Diapositive25.jpeg",
        image3: "img/Diapositive26.jpeg",
        bonne_reponse: 40,
        bonne_image: "img/Diapositive25.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 10,
        ordre_tache: "c1",
        complexite: "simple",
        position_emotion: "eo",
        emotion: "neutre",
        sexe: "F",
        phrase: "sound/simple-eo-4.m4a",
        image1: "img/Diapositive30.jpeg",
        image2: "img/Diapositive29.jpeg",
        image3: "img/Diapositive28.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/Diapositive28.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 7,
        ordre_tache: "c2",
        complexite: "simple",
        position_emotion: "eo",
        emotion: "heureux",
        sexe: "M",
        phrase: "sound/simple-eo-1.m4a",
        image1: "img/Diapositive20.jpeg",
        image2: "img/Diapositive19.jpeg",
        image3: "img/Diapositive21.jpeg",
        bonne_reponse: 40,
        bonne_image: "img/Diapositive19.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 17,
        ordre_tache: "c3",
        complexite: "complexe",
        position_emotion: "es",
        emotion: "furieux",
        sexe: "M",
        phrase: "sound/complexe-es-5.m4a",
        image1: "img/Diapositive49.jpeg",
        image2: "img/Diapositive51.jpeg",
        image3: "img/Diapositive50.jpeg",
        bonne_reponse: 37,
        bonne_image: "img/Diapositive49.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 16,
        ordre_tache: "d1",
        complexite: "complexe",
        position_emotion: "es",
        emotion: "neutre",
        sexe: "F",
        phrase: "sound/complexe-es-4.m4a",
        image1: "img/Diapositive46.jpeg",
        image2: "img/Diapositive47.jpeg",
        image3: "img/Diapositive48.jpeg",
        bonne_reponse: 37,
        bonne_image: "img/Diapositive46.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 1,
        ordre_tache: "d2",
        complexite: "simple",
        position_emotion: "es",
        emotion: "heureux",
        sexe: "M",
        phrase: "sound/simple-es-1.m4a",
        image1: "img/Diapositive3.jpeg",
        image2: "img/Diapositive1.jpeg",
        image3: "img/Diapositive2.jpeg",
        bonne_reponse: 40,
        bonne_image: "img/Diapositive1.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 12,
        ordre_tache: "d3",
        complexite: "simple",
        position_emotion: "eo",
        emotion: "furieux",
        sexe: "F",
        phrase: "sound/simple-eo-6.m4a",
        image1: "img/Diapositive34.jpeg",
        image2: "img/Diapositive35.jpeg",
        image3: "img/Diapositive36.jpeg",
        bonne_reponse: 37,
        bonne_image: "img/Diapositive34.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 11,
        ordre_tache: "e1",
        complexite: "simple",
        position_emotion: "eo",
        emotion: "furieux",
        sexe: "M",
        phrase: "sound/simple-eo-5.m4a",
        image1: "img/Diapositive31.jpeg",
        image2: "img/Diapositive33.jpeg",
        image3: "img/Diapositive32.jpeg",
        bonne_reponse: 37,
        bonne_image: "img/Diapositive31.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 21,
        ordre_tache: "e2",
        complexite: "complexe",
        position_emotion: "eo",
        emotion: "neutre",
        sexe: "M",
        phrase: "sound/complexe-eo-3.m4a",
        image1: "img/Diapositive63.jpeg",
        image2: "img/Diapositive61.jpeg",
        image3: "img/Diapositive62.jpeg",
        bonne_reponse: 40,
        bonne_image: "img/Diapositive61.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 14,
        ordre_tache: "e3",
        complexite: "complexe",
        position_emotion: "es",
        emotion: "heureux",
        sexe: "F",
        phrase: "sound/complexe-es-2.m4a",
        image1: "img/Diapositive42.jpeg",
        image2: "img/Diapositive40.jpeg",
        image3: "img/Diapositive41.jpeg",
        bonne_reponse: 40,
        bonne_image: "img/Diapositive40.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 24,
        ordre_tache: "f1",
        complexite: "complexe",
        position_emotion: "eo",
        emotion: "furieux",
        sexe: "F",
        phrase: "sound/complexe-eo-6.m4a",
        image1: "img/Diapositive70.jpeg",
        image2: "img/Diapositive72.jpeg",
        image3: "img/Diapositive71.jpeg",
        bonne_reponse: 37,
        bonne_image: "img/Diapositive70.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 4,
        ordre_tache: "f2",
        complexite: "simple",
        position_emotion: "es",
        emotion: "neutre",
        sexe: "F",
        phrase: "sound/simple-es-4.m4a",
        image1: "img/Diapositive10.jpeg",
        image2: "img/Diapositive12.jpeg",
        image3: "img/Diapositive11.jpeg",
        bonne_reponse: 37,
        bonne_image: "img/Diapositive10.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 13,
        ordre_tache: "f3",
        complexite: "complexe",
        position_emotion: "es",
        emotion: "heureux",
        sexe: "M",
        phrase: "sound/complexe-es-1.m4a",
        image1: "img/Diapositive38.jpeg",
        image2: "img/Diapositive39.jpeg",
        image3: "img/Diapositive37.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/Diapositive37.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 15,
        ordre_tache: "g1",
        complexite: "complexe",
        position_emotion: "es",
        emotion: "neutre",
        sexe: "M",
        phrase: "sound/complexe-es-3.m4a",
        image1: "img/Diapositive44.jpeg",
        image2: "img/Diapositive43.jpeg",
        image3: "img/Diapositive45.jpeg",
        bonne_reponse: 40,
        bonne_image: "img/Diapositive43.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 6,
        ordre_tache: "g2",
        complexite: "simple",
        position_emotion: "es",
        emotion: "furieux",
        sexe: "F",
        phrase: "sound/simple-es-6.m4a",
        image1: "img/Diapositive17.jpeg",
        image2: "img/Diapositive16.jpeg",
        image3: "img/Diapositive18.jpeg",
        bonne_reponse: 40,
        bonne_image: "img/Diapositive16.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 8,
        ordre_tache: "g3",
        complexite: "simple",
        position_emotion: "eo",
        emotion: "heureux",
        sexe: "F",
        phrase: "sound/simple-eo-2.m4a",
        image1: "img/Diapositive23.jpeg",
        image2: "img/Diapositive24.jpeg",
        image3: "img/Diapositive22.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/Diapositive22.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 20,
        ordre_tache: "h1",
        complexite: "complexe",
        position_emotion: "eo",
        emotion: "heureux",
        sexe: "F",
        phrase: "sound/complexe-eo-2.m4a",
        image1: "img/Diapositive59.jpeg",
        image2: "img/Diapositive58.jpeg",
        image3: "img/Diapositive60.jpeg",
        bonne_reponse: 40,
        bonne_image: "img/Diapositive58.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 3,
        ordre_tache: "h2",
        complexite: "simple",
        position_emotion: "es",
        emotion: "neutre",
        sexe: "M",
        phrase: "sound/simple-es-3.m4a",
        image1: "img/Diapositive8.jpeg",
        image2: "img/Diapositive9.jpeg",
        image3: "img/Diapositive7.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/Diapositive7.jpeg", 
    },
    {
        version: 1,
		bloc: 1,
        ordre_logique: 5,
        ordre_tache: "h3",
        complexite: "simple",
        position_emotion: "es",
        emotion: "furieux",
        sexe: "M",
        phrase: "sound/simple-es-5.m4a",
        image1: "img/Diapositive13.jpeg",
        image2: "img/Diapositive14.jpeg",
        image3: "img/Diapositive15.jpeg",
        bonne_reponse: 37,
        bonne_image: "img/Diapositive13.jpeg", 
    }
];

var stimuli_bloc2_v1 = [
    {
        version: 1,
		bloc: 2,
        ordre_logique: 5,
        ordre_tache: "a1",
        complexite: "simple",
        position_emotion: "es",
        emotion: "furieux",
        sexe: "M",
        phrase: "sound/simple-es-5.m4a",
        image1: "img/Diapositive86.jpeg",
        image2: "img/Diapositive87.jpeg",
        image3: "img/Diapositive85.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/Diapositive85.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 10,
        ordre_tache: "a2",
        complexite: "simple",
        position_emotion: "eo",
        emotion: "neutre",
        sexe: "F",
        phrase: "sound/simple-eo-4.m4a",
        image1: "img/Diapositive102.jpeg",
        image2: "img/Diapositive100.jpeg",
        image3: "img/Diapositive101.jpeg",
        bonne_reponse: 40,
        bonne_image: "img/Diapositive100.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 14,
        ordre_tache: "a3",
        complexite: "complexe",
        position_emotion: "es",
        emotion: "heureux",
        sexe: "F",
        phrase: "sound/complexe-es-2.m4a",
        image1: "img/Diapositive114.jpeg",
        image2: "img/Diapositive113.jpeg",
        image3: "img/Diapositive112.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/Diapositive112.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 13,
        ordre_tache: "b1",
        complexite: "complexe",
        position_emotion: "es",
        emotion: "heureux",
        sexe: "M",
        phrase: "sound/complexe-es-1.m4a",
        image1: "img/Diapositive109.jpeg",
        image2: "img/Diapositive110.jpeg",
        image3: "img/Diapositive111.jpeg",
        bonne_reponse: 37,
        bonne_image: "img/Diapositive109.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 24,
        ordre_tache: "b2",
        complexite: "complexe",
        position_emotion: "eo",
        emotion: "furieux",
        sexe: "F",
        phrase: "sound/complexe-eo-6.m4a",
        image1: "img/Diapositive143.jpeg",
        image2: "img/Diapositive142.jpeg",
        image3: "img/Diapositive144.jpeg",
        bonne_reponse: 40,
        bonne_image: "img/Diapositive142.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 4,
        ordre_tache: "b3",
        complexite: "simple",
        position_emotion: "es",
        emotion: "neutre",
        sexe: "F",
        phrase: "sound/simple-es-4.m4a",
        image1: "img/Diapositive83.jpeg",
        image2: "img/Diapositive82.jpeg",
        image3: "img/Diapositive84.jpeg",
        bonne_reponse: 40,
        bonne_image: "img/Diapositive82.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 20,
        ordre_tache: "c1",
        complexite: "complexe",
        position_emotion: "eo",
        emotion: "heureux",
        sexe: "F",
        phrase: "sound/complexe-eo-2.m4a",
        image1: "img/Diapositive130.jpeg",
        image2: "img/Diapositive132.jpeg",
        image3: "img/Diapositive131.jpeg",
        bonne_reponse: 37,
        bonne_image: "img/Diapositive130.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 16,
        ordre_tache: "c2",
        complexite: "complexe",
        position_emotion: "es",
        emotion: "neutre",
        sexe: "F",
        phrase: "sound/complexe-es-4.m4a",
        image1: "img/Diapositive119.jpeg",
        image2: "img/Diapositive120.jpeg",
        image3: "img/Diapositive118.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/Diapositive118.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 11,
        ordre_tache: "c3",
        complexite: "simple",
        position_emotion: "eo",
        emotion: "furieux",
        sexe: "M",
        phrase: "sound/simple-eo-5.m4a",
        image1: "img/Diapositive105.jpeg",
        image2: "img/Diapositive104.jpeg",
        image3: "img/Diapositive103.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/Diapositive103.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 9,
        ordre_tache: "d1",
        complexite: "simple",
        position_emotion: "eo",
        emotion: "neutre",
        sexe: "M",
        phrase: "sound/simple-eo-3.m4a",
        image1: "img/Diapositive98.jpeg",
        image2: "img/Diapositive97.jpeg",
        image3: "img/Diapositive99.jpeg",
        bonne_reponse: 40,
        bonne_image: "img/Diapositive97.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 7,
        ordre_tache: "d2",
        complexite: "simple",
        position_emotion: "eo",
        emotion: "heureux",
        sexe: "M",
        phrase: "sound/simple-eo-1.m4a",
        image1: "img/Diapositive91.jpeg",
        image2: "img/Diapositive93.jpeg",
        image3: "img/Diapositive92.jpeg",
        bonne_reponse: 37,
        bonne_image: "img/Diapositive91.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 18,
        ordre_tache: "d3",
        complexite: "complexe",
        position_emotion: "es",
        emotion: "furieux",
        sexe: "F",
        phrase: "sound/complexe-es-6.m4a",
        image1: "img/Diapositive126.jpeg",
        image2: "img/Diapositive124.jpeg",
        image3: "img/Diapositive125.jpeg",
        bonne_reponse: 40,
        bonne_image: "img/Diapositive124.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 17,
        ordre_tache: "e1",
        complexite: "complexe",
        position_emotion: "es",
        emotion: "furieux",
        sexe: "M",
        phrase: "sound/complexe-es-5.m4a",
        image1: "img/Diapositive122.jpeg",
        image2: "img/Diapositive121.jpeg",
        image3: "img/Diapositive123.jpeg",
        bonne_reponse: 40,
        bonne_image: "img/Diapositive121.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 21,
        ordre_tache: "e2",
        complexite: "complexe",
        position_emotion: "eo",
        emotion: "neutre",
        sexe: "M",
        phrase: "sound/complexe-eo-3.m4a",
        image1: "img/Diapositive135.jpeg",
        image2: "img/Diapositive134.jpeg",
        image3: "img/Diapositive133.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/Diapositive133.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 2,
        ordre_tache: "e3",
        complexite: "simple",
        position_emotion: "es",
        emotion: "heureux",
        sexe: "F",
        phrase: "sound/simple-es-2.m4a",
        image1: "img/Diapositive78.jpeg",
        image2: "img/Diapositive76.jpeg",
        image3: "img/Diapositive77.jpeg",
        bonne_reponse: 40,
        bonne_image: "img/Diapositive76.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 23,
        ordre_tache: "f1",
        complexite: "complexe",
        position_emotion: "eo",
        emotion: "furieux",
        sexe: "M",
        phrase: "sound/complexe-eo-5.m4a",
        image1: "img/Diapositive141.jpeg",
        image2: "img/Diapositive139.jpeg",
        image3: "img/Diapositive140.jpeg",
        bonne_reponse: 40,
        bonne_image: "img/Diapositive139.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 8,
        ordre_tache: "f2",
        complexite: "simple",
        position_emotion: "eo",
        emotion: "heureux",
        sexe: "F",
        phrase: "sound/simple-eo-2.m4a",
        image1: "img/Diapositive94.jpeg",
        image2: "img/Diapositive95.jpeg",
        image3: "img/Diapositive96.jpeg",
        bonne_reponse: 37,
        bonne_image: "img/Diapositive94.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 15,
        ordre_tache: "f3",
        complexite: "complexe",
        position_emotion: "es",
        emotion: "neutre",
        sexe: "M",
        phrase: "sound/complexe-es-3.m4a",
        image1: "img/Diapositive115.jpeg",
        image2: "img/Diapositive117.jpeg",
        image3: "img/Diapositive116.jpeg",
        bonne_reponse: 37,
        bonne_image: "img/Diapositive115.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 22,
        ordre_tache: "g1",
        complexite: "complexe",
        position_emotion: "eo",
        emotion: "neutre",
        sexe: "F",
        phrase: "sound/complexe-eo-4.m4a",
        image1: "img/Diapositive137.jpeg",
        image2: "img/Diapositive138.jpeg",
        image3: "img/Diapositive136.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/Diapositive136.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 12,
        ordre_tache: "g2",
        complexite: "simple",
        position_emotion: "eo",
        emotion: "furieux",
        sexe: "F",
        phrase: "sound/simple-eo-6.m4a",
        image1: "img/Diapositive107.jpeg",
        image2: "img/Diapositive108.jpeg",
        image3: "img/Diapositive106.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/Diapositive106.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 1,
        ordre_tache: "g3",
        complexite: "simple",
        position_emotion: "es",
        emotion: "heureux",
        sexe: "M",
        phrase: "sound/simple-es-1.m4a",
        image1: "img/Diapositive75.jpeg",
        image2: "img/Diapositive74.jpeg",
        image3: "img/Diapositive73.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/Diapositive73.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 3,
        ordre_tache: "h1",
        complexite: "simple",
        position_emotion: "es",
        emotion: "neutre",
        sexe: "M",
        phrase: "sound/simple-es-3.m4a",
        image1: "img/Diapositive79.jpeg",
        image2: "img/Diapositive80.jpeg",
        image3: "img/Diapositive81.jpeg",
        bonne_reponse: 37,
        bonne_image: "img/Diapositive79.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 6,
        ordre_tache: "h2",
        complexite: "simple",
        position_emotion: "es",
        emotion: "furieux",
        sexe: "F",
        phrase: "sound/simple-es-6.m4a",
        image1: "img/Diapositive88.jpeg",
        image2: "img/Diapositive90.jpeg",
        image3: "img/Diapositive89.jpeg",
        bonne_reponse: 37,
        bonne_image: "img/Diapositive88.jpeg", 
    },
    {
        version: 1,
		bloc: 2,
        ordre_logique: 19,
        ordre_tache: "h3",
        complexite: "complexe",
        position_emotion: "eo",
        emotion: "heureux",
        sexe: "M",
        phrase: "sound/complexe-eo-1.m4a",
        image1: "img/Diapositive127.jpeg",
        image2: "img/Diapositive128.jpeg",
        image3: "img/Diapositive129.jpeg",
        bonne_reponse: 37,
        bonne_image: "img/Diapositive127.jpeg", 
    }
];