var stimuli_pratique = [
	{
        bloc: 0,
        ordre_logique: 3,
        ordre_tache: "1",
        emotion: "neutre",
        sexe: "M",
        mot: "sound/pensif.m4a",
        image1: "img/pensif.jpeg",
        image2: "img/heureux-gris.jpeg",
        image3: "img/furieux-gris.jpeg",
        bonne_reponse: 37
    },
    {
        bloc: 0,
        ordre_logique: 6,
        ordre_tache: "2",
        emotion: "furieux",
        sexe: "F",
        mot: "sound/furieuse.m4a",
        image1: "img/pensive-gris.jpeg",
        image2: "img/heureuse-gris.jpeg",
        image3: "img/furieuse.jpeg",
        bonne_reponse: 39
    },
    {
        bloc: 0,
        ordre_logique: 5,
        ordre_tache: "3",
        emotion: "furieux",
        sexe: "M",
        mot: "sound/furieux.m4a",
        image1: "img/heureux-gris.jpeg",
        image2: "img/furieux.jpeg",
        image3: "img/pensif-gris.jpeg",
        bonne_reponse: 40
    },
    {
        bloc: 0,
        ordre_logique: 1,
        ordre_tache: "4",
        emotion: "heureux",
        sexe: "M",
        mot: "sound/heureux.m4a",
        image1: "img/furieux-gris.jpeg",
        image2: "img/pensif-gris.jpeg",
        image3: "img/heureux.jpeg",
        bonne_reponse: 39
    },
    {
        bloc: 0,
        ordre_logique: 4,
        ordre_tache: "5",
        emotion: "neutre",
        sexe: "F",
        mot: "sound/pensive.m4a",
        image1: "img/furieuse-gris.jpeg",
        image2: "img/pensive.jpeg",
        image3: "img/heureuse-gris.jpeg",
        bonne_reponse: 40
    },
    {
        bloc: 0,
        ordre_logique: 2,
        ordre_tache: "6",
        emotion: "heureux",
        sexe: "F",
        mot: "sound/heureuse.m4a",
        image1: "img/heureuse.jpeg",
        image2: "img/furieuse-gris.jpeg",
        image3: "img/pensive-gris.jpeg",
        bonne_reponse: 37
    }
];

var stimuli = [
    {
        bloc: 1,
        ordre_logique: 1,
        ordre_tache: "d2",
        complexite: "simple",
        position_emotion: "es",
        emotion: "heureux",
        sexe_sujet: "M",
        phrase: "sound/simple-es-1.m4a",
        image1: "img/Diapositive3.jpeg",
        image2: "img/Diapositive1.jpeg",
        image3: "img/Diapositive2.jpeg",
        bonne_reponse: 40,
        bonne_image: "img/Diapositive1.jpeg", 
    },
    {
        bloc: 1,
        ordre_logique: 7,
        ordre_tache: "c2",
        complexite: "simple",
        position_emotion: "eo",
        emotion: "heureux",
        sexe_sujet: "M",
        phrase: "sound/simple-eo-1.m4a",
        image1: "img/Diapositive20.jpeg",
        image2: "img/Diapositive19.jpeg",
        image3: "img/Diapositive21.jpeg",
        bonne_reponse: 40,
        bonne_image: "img/Diapositive19.jpeg", 
    },
    {
        bloc: 1,
        ordre_logique: 13,
        ordre_tache: "f3",
        complexite: "complexe",
        position_emotion: "es",
        emotion: "heureux",
        sexe_sujet: "M",
        phrase: "sound/complexe-es-1.m4a",
        image1: "img/Diapositive38.jpeg",
        image2: "img/Diapositive39.jpeg",
        image3: "img/Diapositive37.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/Diapositive37.jpeg", 
    },
    {
        bloc: 1,
        ordre_logique: 19,
        ordre_tache: "b2",
        complexite: "complexe",
        position_emotion: "eo",
        emotion: "heureux",
        sexe_sujet: "M",
        phrase: "sound/complexe-eo-1.m4a",
        image1: "img/Diapositive56.jpeg",
        image2: "img/Diapositive57.jpeg",
        image3: "img/Diapositive55.jpeg",
        bonne_reponse: 39,
        bonne_image: "img/Diapositive55.jpeg", 
    },
];
